"""email change

Revision ID: 95790c20f30f
Revises: 2873fb4e5e79
Create Date: 2019-12-06 20:06:53.103007

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95790c20f30f'
down_revision = '2873fb4e5e79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_email', table_name='user')
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.create_index('ix_user_email', 'user', ['email'], unique=1)
    # ### end Alembic commands ###
